id: P000572
initial_creation_type: ocr
source_metadata:
  id: bdr:W2DB4614
  title: རྒྱུད་བླའི་ཊཱི་ཀ
  author: ''
  volumes:
    37b1539d6c8c4d99a141fe73f17dd4fb:
      image_group_id: I00KG09397
      title: Volume 1 of rgyud bla'i TI ka
      volume_number: 1
      total_pages: 310
      base_file: v001.txt
ebook_metadata:
  title: རྒྱུད་བླའི་ཊཱི་ཀ
  author: ''
  sku: P000572
  cover: cover.jpg
  layers:
  - pagination
